config/routes.rb
Rails.application.routes.draw do
  get 'tasks/:task_id/new-user(.:format)', to: 'tasks#new_join_user', as: 'new_join_user'
  post 'tasks/:task_id/new-user(.:format)', to: 'tasks#create_join_user', as: 'create_join_user'

  delete 'tasks/:task_id/users/:id(.:format)', to: 'tasks#delete_join_user', as: 'delete_join_user'

  resources :tasks do
      resources :users, only: [:show]
  end

  resources :projects do
    resources :tasks, shallow: true
  end

  #resources :tasks
  resources :statuses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  root 'projects#index'
  get '/projects', to: 'projects#index', as: 'user_root'
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin?

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: 'Status was successfully created.' }
        format.json { render :index, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to statuses_url, notice: 'Status was successfully updated.' }
        format.json { render :index, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    respond_to do |format|
      if @status.destroy
        format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to statuses_url, notice: 'Status was not destroyed.'  }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:title)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-outline-success btn-lg" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>
<%= link_to 'Back', statuses_path, class: "btn btn-outline-dark my-2 my-sm-0" %>

app/views/statuses/index.html.erb
<h4>Statuses</h4>
<div class="row">
  <div class="col-2">
      <strong>Title</strong>
  </div>
</div>

<% @statuses.each do |status| %>
<div class="row mb-2">
  <div class="col-2">
    <%= status.title %>
  </div>
  <div class="col-1">
    <%= link_to 'Edit', edit_status_path(status),  class: "btn btn-outline-warning btn-block btn-sm" %>
  </div>
  <div class="col-1">
    <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block btn-sm" %>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-4">
    <%= link_to 'New Status', new_status_path, class: "btn btn-outline-success btn-block" %>
  </div>
</div>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path, class: "btn btn-outline-dark" %>

app/views/statuses/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @status.title %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>