config/routes.rb
Rails.application.routes.draw do
  get 'tasks/:task_id/new-user(.:format)', to: 'tasks#new_join_user', as: 'new_join_user'
  post 'tasks/:task_id/new-user(.:format)', to: 'tasks#create_join_user', as: 'create_join_user'

  delete 'tasks/:task_id/users/:id(.:format)', to: 'tasks#delete_join_user', as: 'delete_join_user'

  resources :tasks do
      resources :users, only: [:show]
  end

  resources :projects do
    resources :tasks, shallow: true
  end

  #resources :tasks
  resources :statuses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  root 'projects#index'
  get '/projects', to: 'projects#index', as: 'user_root'
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :project
  has_many :task_items
  has_many :users, through: :task_items, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :project }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin?, only: [:edit, :update, :destroy, :delete_join_user, :new_join_user, :create_join_user]

  # GET /tasks
  # GET /tasks.json
  def index
    if current_user.admin?
      @tasks=Task.all
    else
      @tasks = current_user.tasks
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_join_user
    @task=Task.find(params[:task_id])
    #@users=User.where("users.id NOT IN (?)", @task.users.pluck(:user_id))
    @users=User.where.not(id: @task.users.pluck(:user_id))
  end

  def delete_join_user
    @task=Task.find(params[:task_id])
    @user=User.find(params[:id])
    @task.users.delete(@user)
    respond_to do |format|
      format.html { redirect_to task_url(@task), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_join_user
    @task=Task.find(params[:task_id])
    @user=User.find(params[:user][:id])
    @task.task_items.create(user: @user)
    respond_to do |format|
      format.html { redirect_to @task, notice: 'User was successfully added.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :status_id, :project_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning" role="alert">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :status_id %>
    <%= form.collection_select(:status_id, Status.all, :id, :title, class: "form-control", required: true) %>
  </div>

  <div class="form-group">
    <%= form.label :project_id %>
    <%= form.collection_select(:project_id, Project.all, :id, :name, class: "form-control", required: true) %>
  </div>

  <div class="form-group">
    <%= form.submit "submit", class: "btn btn-outline-success btn-lg"%>
  </div>
<% end %>

app/views/tasks/_main_information.html.erb
<div class="row mb-2">
  <div class="col-2">
    <%= task.title %>
  </div>
  <div class="col-3">
    <%= task.description %>
  </div>
  <div class="col-2">
    <%= task.status.title %>
  </div>
  <div class="col-2">
    <%= task.project.name %>
  </div>
  <% if action_name != "show" %>
  <div class="col-1">
    <%= link_to 'Show', task, class: "btn btn-outline-info btn-block btn-sm" %>
  </div>
  <% end %>
  <% if current_user.admin? %>
  <div class="col-1">
    <%= link_to 'Edit', edit_task_path(task), class: "btn btn-outline-warning btn-block btn-sm" %>
  </div>
  <div class="col-1">
    <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block btn-sm" %>
  </div>
  <% end %>
</div>

app/views/tasks/_regular_information.html.erb
<h4><%= title %></h4>
  <div class="row">
    <div class="col-2">
        <strong>Title</strong>
    </div>
    <div class="col-3">
        <strong>Description</strong>
    </div>
    <div class="col-2">
        <strong>Status</strong>
    </div>
    <div class="col-2">
        <strong>Project</strong>
    </div>
  </div>

app/views/tasks/edit.html.erb
  <div class="row">
    <div class="col-12">
      <h4>Editing Task</h1>
    </div>
  </div>
  <%= render 'form', task: @task %>
  <%= link_to 'Back', task_path(@task), class: "btn btn-outline-dark my-2 my-sm-0" %>

app/views/tasks/index.html.erb
<% if @tasks.any? %>
<%= render 'regular_information', title: "Tasks" %>
  <% @tasks.each do |task| %>
    <%= render partial: "main_information", locals: { task: task } %>
  <% end %>
<% else %>
  <h5>You don't have active tasks</h5>
<% end %>
    <% if current_user.admin? %>
    <div class="row">
      <div class="col-12">
        <%= link_to 'New Task', new_task_path, class: "btn btn-outline-success btn-block btn-sm" if current_user.admin? %>
      </div>
    </div>
    <% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new_join_user.html.erb
<h4>Adding New User For Task</h4>
<% if @users.empty? %>
  <strong>All users already added for this task</strong>
<% else %>
<%= form_for :user do |form| %>
  <div class="form-group">
  <%= form.collection_select(:id, @users, :id, :first_name, class: "form-control", required: true) %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-outline-success btn-lg"%>
  </div>
<% end %>
<% end %>

app/views/tasks/show.html.erb
<%= render 'regular_information', title: "Task info" %>
<%= render partial: "main_information", locals: { task: @task } %>
<div class="row">
  <div class="col-12 text-center">
    <strong>Users</strong>
  </div>
</div>
<% if current_user.admin? %>
<div class="row mb-2">
  <div class="col-12">
    <%= link_to "New User", new_join_user_path(@task), class: "btn btn-outline-success btn-sm btn-block" %>
  </div>
</div>
<% end %>

  <% @tasks=current_user.tasks.where(project: @project) %>
  <% if @task.users.empty? %>
  <div class="row">
    <div class="col-12 text-center">
      Users not exist for this task
    </div>
  </div>
  <% else %>
  <% @task.users.each do |user| %>
    <div class="row mb-2">
      <div class="col-10">
        <%= "#{user.first_name} #{user.last_name} #{user.email}" %>
      </div>
      <% if current_user.admin? %>
      <div class="col-1">
          <%= link_to "Show", task_user_path(@task, user), class: "btn btn-outline-info btn-sm btn-block" %>
      </div>
      <div class="col-1">
          <%= link_to 'Unsubscribe', delete_join_user_path(@task, user), method: :delete,  data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
      </div>
      <% end %>
  </div>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-12 text-center">
      <%= link_to 'Back', project_path(@task.project), class: "btn btn-outline-dark my-2 my-sm-0" %>
    </div>
  </div>