config/routes.rb
Rails.application.routes.draw do
  get 'tasks/:task_id/new-user(.:format)', to: 'tasks#new_join_user', as: 'new_join_user'
  post 'tasks/:task_id/new-user(.:format)', to: 'tasks#create_join_user', as: 'create_join_user'

  delete 'tasks/:task_id/users/:id(.:format)', to: 'tasks#delete_join_user', as: 'delete_join_user'

  resources :tasks do
      resources :users, only: [:show]
  end

  resources :projects do
    resources :tasks, shallow: true
  end

  #resources :tasks
  resources :statuses
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  root 'projects#index'
  get '/projects', to: 'projects#index', as: 'user_root'
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, length: {maximum: 100}, presence: true, uniqueness: { case_sensitive: false }
  validates :summary, presence: true
  has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin?, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if current_user.admin?
      @projects=Project.all
    else
      @projects = current_user.projects.distinct
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :summary, :start_date, :end_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="alert alert-warning" role="alert">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: "btn btn-outline-success btn-lg" %>
  </div>
<% end %>

app/views/projects/_main_information.html.erb
<div class="row mb-2">
  <div class="col-2">
    <%= project.name %>
  </div>
  <div class="col-3">
    <%= project.summary %>
  </div>
  <div class="col-2">
    <%= project.start_date.strftime("%d.%m.%Y") %>
  </div>
  <div class="col-2">
    <%= project.end_date.strftime("%d.%m.%Y") %>
  </div>
  <% if action_name != "show" %>
  <div class="col-1">
    <%= link_to 'Show', project, class: "btn btn-outline-info btn-block btn-sm" %>
  </div>
  <% end %>
  <% if current_user.admin? %>
  <div class="col-1">
    <%= link_to 'Edit', edit_project_path(project), class: "btn btn-outline-warning btn-block btn-sm" %>
  </div>
  <div class="col-1">
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block btn-sm" %>
  </div>
  <% end %>
</div>

app/views/projects/_regular_information.html.erb
<h4><%= title %></h4>
<div class="row">
  <div class="col-2">
      <strong>Name</strong>
  </div>
  <div class="col-3">
      <strong>Summary</strong>
  </div>
  <div class="col-2">
      <strong>Start date</strong>
  </div>
  <div class="col-2">
      <strong>End date</strong>
  </div>
</div>

app/views/projects/edit.html.erb
  <div class="row">
    <div class="col-12">
      <h4>Editing Project</h1>
    </div>
  </div>
  <%= render 'form', project: @project %>
  <%= link_to 'Back', :back, class: "btn btn-outline-dark my-2 my-sm-0" %>

app/views/projects/index.html.erb
<% if @projects.any? %>
<%= render 'regular_information', title: "Projects" %>
<% @projects.each do |project| %>
  <%= render partial: "main_information", locals: { project: project } %>
  <% end %>
<% else %>
  <h5>You don't have active projects</h5>
<% end %>
<% if current_user.admin? %>
  <div class="row">
    <div class="col-12">
      <%= link_to 'New Project', new_project_path, class: "btn btn-outline-success btn-block btn-sm" %>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-12">
    <h4>New Project</h1>
  </div>
</div>
<%= render 'form', project: @project %>
<%= link_to 'Back', :back, class: "btn btn-outline-dark my-2 my-sm-0" %>

app/views/projects/show.html.erb
<%= render 'regular_information', title: "Project info" %>
<%= render partial: "main_information", locals: { project: @project } %>

<div class="row">
  <div class="col-12 text-center">
    <strong>Tasks</strong>
  </div>
</div>
<% if current_user.admin? %>
<div class="row mb-2">
  <div class="col-12">
    <%= link_to "New Task", new_project_task_path(@project), class: "btn btn-outline-success btn-sm btn-block" %>
  </div>
</div>
<% end %>

  <% @tasks=current_user.tasks.where(project: @project) %>
  <% if @tasks.empty? %>
  <div class="row">
    <div class="col-12 text-center">
      Tasks not exist for this project
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-3">
      <strong>Title</strong>
    </div>
    <div class="col-3">
      <strong>Description</strong>
    </div>
    <div class="col-3">
      <strong>Status</strong>
    </div>
  </div>
  <% @tasks.each do |task| %>
  <div class="row mb-2">
    <div class="col-3">
      <%= task.title %>
    </div>
    <div class="col-3">
      <%= task.description %>
    </div>
    <div class="col-3">
      <%= task.status.title %>
    </div>
    <div class="col-1">
      <%= link_to 'Show', task_path(task), class: "btn btn-outline-info btn-block btn-sm" %>
    </div>
    <% if current_user.admin? %>
    <div class="col-1">
      <%= link_to 'Edit', edit_task_path(task), class: "btn btn-outline-warning btn-block btn-sm" %>
    </div>
    <div class="col-1">
      <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block btn-sm" %>
    </div>
    <% end %>
  </div>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-12 text-center">
      <%= link_to 'Back', root_path, class: "btn btn-outline-dark my-2 my-sm-0" %>
    </div>
  </div>